/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.Clientes.ClientePrincipal;
import java.awt.Color;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import view.Funcionarios.FuncionarioPrincipal;
import view.Servicos.ServicoPrincipal;
/**
 *
 * @author Jonas Santos
 */
public class PaginaInicial extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipal
     */
    public PaginaInicial() {
        initComponents();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTitulo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbMenu = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btCliente = new javax.swing.JButton();
        btServico = new javax.swing.JButton();
        btRelatorio = new javax.swing.JButton();
        btCabeleireiro = new javax.swing.JButton();
        btMovimentacao = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        pnCentral = new javax.swing.JPanel();
        painelImagemFundo1 = new view.painelImagemFundo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(760, 300));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        pnTitulo.setBackground(new java.awt.Color(0, 0, 0));
        pnTitulo.setName(""); // NOI18N
        pnTitulo.setPreferredSize(new java.awt.Dimension(684, 0));
        pnTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Impact", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnTitulo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 280, -1));

        getContentPane().add(pnTitulo, java.awt.BorderLayout.PAGE_START);

        pnMenu.setBackground(new java.awt.Color(0, 0, 0));
        pnMenu.setForeground(new java.awt.Color(51, 51, 51));
        pnMenu.setMaximumSize(new java.awt.Dimension(380, 344));
        pnMenu.setPreferredSize(new java.awt.Dimension(220, 300));
        pnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(80, 2));
        jLabel1.setMinimumSize(new java.awt.Dimension(80, 2));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 1));
        pnMenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 129, 180, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Barber Shop");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnMenu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 93, 220, 30));

        lbMenu.setBackground(new java.awt.Color(0, 0, 0));
        lbMenu.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        lbMenu.setForeground(new java.awt.Color(240, 240, 240));
        lbMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Logo.jpg"))); // NOI18N
        lbMenu.setText(" ");
        lbMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbMenu.setMaximumSize(new java.awt.Dimension(300, 120));
        lbMenu.setMinimumSize(new java.awt.Dimension(15, 100));
        lbMenu.setOpaque(true);
        lbMenu.setPreferredSize(new java.awt.Dimension(10, 50));
        pnMenu.add(lbMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 100));

        jLabel3.setText("  ");
        pnMenu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        btCliente.setBackground(new java.awt.Color(0, 0, 0));
        btCliente.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btCliente.setForeground(new java.awt.Color(255, 255, 255));
        btCliente.setText("Clientes");
        btCliente.setToolTipText("");
        btCliente.setBorderPainted(false);
        btCliente.setContentAreaFilled(false);
        btCliente.setFocusPainted(false);
        btCliente.setMaximumSize(new java.awt.Dimension(230, 50));
        btCliente.setMinimumSize(new java.awt.Dimension(120, 45));
        btCliente.setOpaque(true);
        btCliente.setPreferredSize(new java.awt.Dimension(180, 50));
        btCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btClienteMouseExited(evt);
            }
        });
        btCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClienteActionPerformed(evt);
            }
        });
        pnMenu.add(btCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 136, 220, -1));

        btServico.setBackground(new java.awt.Color(0, 0, 0));
        btServico.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btServico.setForeground(new java.awt.Color(255, 255, 255));
        btServico.setText("Serviços");
        btServico.setToolTipText("");
        btServico.setBorderPainted(false);
        btServico.setContentAreaFilled(false);
        btServico.setFocusPainted(false);
        btServico.setMaximumSize(new java.awt.Dimension(230, 50));
        btServico.setMinimumSize(new java.awt.Dimension(120, 45));
        btServico.setOpaque(true);
        btServico.setPreferredSize(new java.awt.Dimension(180, 45));
        btServico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btServicoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btServicoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btServicoMouseExited(evt);
            }
        });
        pnMenu.add(btServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 186, 220, 50));

        btRelatorio.setBackground(new java.awt.Color(0, 0, 0));
        btRelatorio.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btRelatorio.setForeground(new java.awt.Color(255, 255, 255));
        btRelatorio.setText("Relatórios");
        btRelatorio.setToolTipText("");
        btRelatorio.setBorderPainted(false);
        btRelatorio.setContentAreaFilled(false);
        btRelatorio.setFocusPainted(false);
        btRelatorio.setMaximumSize(new java.awt.Dimension(230, 50));
        btRelatorio.setMinimumSize(new java.awt.Dimension(120, 45));
        btRelatorio.setOpaque(true);
        btRelatorio.setPreferredSize(new java.awt.Dimension(180, 45));
        btRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btRelatorioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btRelatorioMouseExited(evt);
            }
        });
        pnMenu.add(btRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 236, 220, 50));

        btCabeleireiro.setBackground(new java.awt.Color(0, 0, 0));
        btCabeleireiro.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btCabeleireiro.setForeground(new java.awt.Color(255, 255, 255));
        btCabeleireiro.setText("Funcionarios");
        btCabeleireiro.setToolTipText("");
        btCabeleireiro.setBorderPainted(false);
        btCabeleireiro.setContentAreaFilled(false);
        btCabeleireiro.setFocusPainted(false);
        btCabeleireiro.setMaximumSize(new java.awt.Dimension(230, 50));
        btCabeleireiro.setMinimumSize(new java.awt.Dimension(120, 45));
        btCabeleireiro.setOpaque(true);
        btCabeleireiro.setPreferredSize(new java.awt.Dimension(180, 45));
        btCabeleireiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btCabeleireiroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btCabeleireiroMouseExited(evt);
            }
        });
        btCabeleireiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCabeleireiroActionPerformed(evt);
            }
        });
        pnMenu.add(btCabeleireiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 286, 220, 50));

        btMovimentacao.setBackground(new java.awt.Color(0, 0, 0));
        btMovimentacao.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btMovimentacao.setForeground(new java.awt.Color(255, 255, 255));
        btMovimentacao.setText("Movimentação");
        btMovimentacao.setToolTipText("");
        btMovimentacao.setBorderPainted(false);
        btMovimentacao.setContentAreaFilled(false);
        btMovimentacao.setFocusPainted(false);
        btMovimentacao.setMaximumSize(new java.awt.Dimension(230, 50));
        btMovimentacao.setMinimumSize(new java.awt.Dimension(120, 45));
        btMovimentacao.setOpaque(true);
        btMovimentacao.setPreferredSize(new java.awt.Dimension(180, 45));
        btMovimentacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btMovimentacaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btMovimentacaoMouseExited(evt);
            }
        });
        pnMenu.add(btMovimentacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 336, 220, 50));

        btSair.setBackground(new java.awt.Color(0, 0, 0));
        btSair.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btSair.setForeground(new java.awt.Color(255, 255, 255));
        btSair.setText("Sair");
        btSair.setToolTipText("");
        btSair.setBorderPainted(false);
        btSair.setContentAreaFilled(false);
        btSair.setFocusPainted(false);
        btSair.setMaximumSize(new java.awt.Dimension(230, 50));
        btSair.setMinimumSize(new java.awt.Dimension(120, 45));
        btSair.setOpaque(true);
        btSair.setPreferredSize(new java.awt.Dimension(180, 45));
        btSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btSairMouseExited(evt);
            }
        });
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        pnMenu.add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 386, 220, 50));

        getContentPane().add(pnMenu, java.awt.BorderLayout.LINE_START);

        pnCentral.setBackground(new java.awt.Color(218, 239, 249));
        pnCentral.setPreferredSize(new java.awt.Dimension(400, 200));

        painelImagemFundo1.setImg(new ImageIcon("src/Resources/FundoTelaInicial.jpg"));

        javax.swing.GroupLayout painelImagemFundo1Layout = new javax.swing.GroupLayout(painelImagemFundo1);
        painelImagemFundo1.setLayout(painelImagemFundo1Layout);
        painelImagemFundo1Layout.setHorizontalGroup(
            painelImagemFundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        painelImagemFundo1Layout.setVerticalGroup(
            painelImagemFundo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnCentralLayout = new javax.swing.GroupLayout(pnCentral);
        pnCentral.setLayout(pnCentralLayout);
        pnCentralLayout.setHorizontalGroup(
            pnCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelImagemFundo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnCentralLayout.setVerticalGroup(
            pnCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelImagemFundo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(pnCentral, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClienteActionPerformed
    
            ClientePrincipal tela = new ClientePrincipal();
            tela.setVisible(true);

    }//GEN-LAST:event_btClienteActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void btClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btClienteMouseEntered
        setButton(btCliente);
    }//GEN-LAST:event_btClienteMouseEntered

    private void btClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btClienteMouseExited
        resetButton(btCliente);
    }//GEN-LAST:event_btClienteMouseExited

    private void btServicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btServicoMouseEntered
        setButton(btServico);
    }//GEN-LAST:event_btServicoMouseEntered

    private void btServicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btServicoMouseExited
        resetButton(btServico);
    }//GEN-LAST:event_btServicoMouseExited

    private void btRelatorioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRelatorioMouseEntered
        setButton(btRelatorio);
    }//GEN-LAST:event_btRelatorioMouseEntered

    private void btRelatorioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRelatorioMouseExited
        resetButton(btRelatorio);
    }//GEN-LAST:event_btRelatorioMouseExited

    private void btCabeleireiroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCabeleireiroMouseEntered
        setButton(btCabeleireiro);
    }//GEN-LAST:event_btCabeleireiroMouseEntered

    private void btCabeleireiroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCabeleireiroMouseExited
        resetButton(btCabeleireiro);
    }//GEN-LAST:event_btCabeleireiroMouseExited

    private void btMovimentacaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMovimentacaoMouseEntered
        setButton(btMovimentacao);
    }//GEN-LAST:event_btMovimentacaoMouseEntered

    private void btMovimentacaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMovimentacaoMouseExited
        resetButton(btMovimentacao);
    }//GEN-LAST:event_btMovimentacaoMouseExited

    private void btSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSairMouseEntered
        setButton(btSair);
    }//GEN-LAST:event_btSairMouseEntered

    private void btSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSairMouseExited
        resetButton(btSair);
    }//GEN-LAST:event_btSairMouseExited

    private void btServicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btServicoMouseClicked
        ServicoPrincipal tela = new ServicoPrincipal();
        tela.setVisible(true);
    }//GEN-LAST:event_btServicoMouseClicked

    private void btCabeleireiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCabeleireiroActionPerformed
        FuncionarioPrincipal tela = new FuncionarioPrincipal();
        tela.setVisible(true);
    }//GEN-LAST:event_btCabeleireiroActionPerformed

    private static void setButton(JButton botao){
        botao.setBackground(new Color(58,58,58));
        botao.setFont(new Font("Trebuchet MS",1,19));
    }
    
    private static void resetButton(JButton botao){
        botao.setBackground(new Color(0,0,0));
        botao.setFont(new Font("Trebuchet MS",1,18));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCabeleireiro;
    private javax.swing.JButton btCliente;
    private javax.swing.JButton btMovimentacao;
    private javax.swing.JButton btRelatorio;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbMenu;
    private view.painelImagemFundo painelImagemFundo1;
    private javax.swing.JPanel pnCentral;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnTitulo;
    // End of variables declaration//GEN-END:variables
}
