/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Movimentacao;

import Util.Mascara;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.ProdutosMovimento;
import model.Servico;

/**
 *
 * @author Jonas Santos
 */
public class IncluirProdutoMovimentacao extends javax.swing.JFrame {

    /**
     * Creates new form IncluirProdutoMovimentacao
     */
    double valorUnitario;
    ProdutosMovimento produtos;
    public IncluirProdutoMovimentacao(Servico servico) {
        initComponents();
        valorUnitario=servico.getPreco();
        txtCodigo.setText(String.valueOf(servico.getCodigo()));
        txtDescricao.setText(servico.getDescricao());
        setMask();
        txtValor.setText(String.format("%.2f",valorUnitario));
        calculaTotal();
    }

    IncluirProdutoMovimentacao() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCodigo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtDescricao = new javax.swing.JTextField();
        lbDescricao = new javax.swing.JLabel();
        lbQtde = new javax.swing.JLabel();
        txtQtde = new javax.swing.JTextField();
        lbValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JFormattedTextField();
        lbTotal = new javax.swing.JLabel();
        btEfetivar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        txtTotal = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 122));
        setPreferredSize(new java.awt.Dimension(450, 122));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbCodigo.setText("Codigo");
        getContentPane().add(lbCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 49, 40, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Incluir Produto");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 421, -1));

        txtCodigo.setEditable(false);
        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 46, 60, -1));

        txtDescricao.setEditable(false);
        txtDescricao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 46, 180, -1));

        lbDescricao.setText("Descrição");
        getContentPane().add(lbDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 49, 60, -1));

        lbQtde.setText("Quantidade");
        getContentPane().add(lbQtde, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 87, -1, -1));

        txtQtde.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQtde.setText("1");
        txtQtde.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQtdeFocusLost(evt);
            }
        });
        getContentPane().add(txtQtde, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 84, 40, -1));

        lbValor.setText("Valor");
        getContentPane().add(lbValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 87, 38, -1));

        txtValor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorFocusLost(evt);
            }
        });
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 84, 70, -1));

        lbTotal.setText("Total");
        getContentPane().add(lbTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 87, 30, -1));

        btEfetivar.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btEfetivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botaoefetivar5.png"))); // NOI18N
        btEfetivar.setText("Efetivar");
        btEfetivar.setBorderPainted(false);
        btEfetivar.setContentAreaFilled(false);
        btEfetivar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btEfetivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEfetivarActionPerformed(evt);
            }
        });
        getContentPane().add(btEfetivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 100, 40));

        btCancelar.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/botaocancelar6.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.setBorderPainted(false);
        btCancelar.setContentAreaFilled(false);
        btCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 100, 40));

        txtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTotal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTotalFocusLost(evt);
            }
        });
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 84, 90, -1));

        setSize(new java.awt.Dimension(437, 195));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btEfetivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEfetivarActionPerformed
        try{
            List<ProdutosMovimento> listProd = new ArrayList<ProdutosMovimento>();
            int codigo;
            codigo=Integer.parseInt(txtCodigo.getText());
            int qtde = Integer.parseInt(txtQtde.getText());
            double valorUnitario=Double.parseDouble(txtValor.getText().replace(",", "."));
            double valorTotal=Double.parseDouble(txtTotal.getText().replace(",", "."));
            
            Servico servico = new Servico(codigo,txtDescricao.getText());
            ProdutosMovimento incluir = new ProdutosMovimento(servico,qtde,valorUnitario,valorTotal);
            
            listProd.add(incluir);
            CarregaGrid(listProd);
            //incluir.setListaProduto(incluir);                        
            this.dispose();
        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao adicionar Produto!");
        }        
        
    }//GEN-LAST:event_btEfetivarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void txtQtdeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQtdeFocusLost
        calculaTotal();
    }//GEN-LAST:event_txtQtdeFocusLost

    private void txtValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorFocusLost
        calculaTotal();
    }//GEN-LAST:event_txtValorFocusLost

    private void txtTotalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTotalFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalFocusLost
    private void setMask(){
        txtValor.setFormatterFactory(Mascara.getValorMask());
        txtTotal.setFormatterFactory(Mascara.getValorMask());
    }

    private void calculaTotal(){
        int qtde=Integer.valueOf(txtQtde.getText());
        double total;
        valorUnitario=Double.parseDouble(txtValor.getText().replace(",", "."));
        total=valorUnitario*qtde;
        txtTotal.setText(String.format("%.2f",total));
    }
    
    private void CarregaGrid(List<ProdutosMovimento> listProd){
        IncluirMovimento carrega = new IncluirMovimento();
        //carrega.carregaGrid(listProd);
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IncluirProdutoMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IncluirProdutoMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IncluirProdutoMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IncluirProdutoMovimentacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IncluirProdutoMovimentacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btEfetivar;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JLabel lbQtde;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbValor;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtQtde;
    private javax.swing.JFormattedTextField txtTotal;
    private javax.swing.JFormattedTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
